version: '3.9'

# Define environment variables
x-env: &default-env
  NODE_ENV: prod

services:
  backend:
    command: "sh -c 'chmod -R 777 /root && cd /app && npm install && npx prisma migrate deploy && npm run start'"

  frontend:
    command: "sh -c 'chmod -R 777 /root && cd /app && npm install && npm run build && npm run start'"
