version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pong
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    image: node:16-alpine
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    entrypoint: "sh -c 'chmod -R 777 /root && cd /app && npx yarn && npx prisma db push && npx yarn run start'"
#    command: tail -F anything
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_NAME=pong
      - NODE_ENV=development
      - DB_PORT=5432
      - DB_HOST=db

  frontend:
    image: node:16-alpine
    restart: always
    ports:
      - 3040:3040
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    entrypoint: "sh -c 'chmod -R 777 /root && cd /app && npx yarn && npx yarn dev'"
#    command: tail -F anything
    environment:
      GRAPHQL_REMOTE: http://localhost:3000/graphql
