version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pong
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    image: node:16-alpine
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    entrypoint: "sh -c 'chmod -R 777 /root && cd /app && npx yarn && npx prisma migrate deploy && npm run start'"
#    command: tail -F anything
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_NAME=pong
      - NODE_ENV=development
      - DB_PORT=5432
      - DB_HOST=db
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pong?schema=public

  frontend:
    image: node:16-alpine
    container_name: frontend
    restart: always
    ports:
      - 3040:3040
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    entrypoint: "sh -c 'chmod -R 777 /root && cd /app && npm install && npm run dev'"
    # entrypoint: "sh -c 'chmod -R 777 /root && cd /app && npx yarn && npx yarn build && npx yarn start'"
    environment:
      - BACKEND_HOST=localhost
      - BACKEND_PORT=80

  web:
    image: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
